# Generated by Django 2.2.4 on 2019-08-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_blog', '0002_auto_20190827_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prouser',
            options={'verbose_name': ''},
        ),
        migrations.AlterModelTable(
            name='prouser',
            table='프로사용자',
        ),
    ]
