# Generated by Django 2.2.4 on 2019-08-27 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_blog', '0003_auto_20190827_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='prouser',
            options={'verbose_name': '프로사용자들', 'verbose_name_plural': '프로사용자들'},
        ),
        migrations.CreateModel(
            name='GotBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('original_name', models.CharField(max_length=100)),
                ('search_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_blog.SearchResult')),
            ],
        ),
    ]
