# Generated by Django 2.2.4 on 2019-08-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_blog', '0005_auto_20190827_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='gotblog',
            name='content_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gotblog',
            name='original_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gotblog',
            name='original_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gotblog',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
